name: ChopChop YAML configuration Linter

on: [push]

jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: yaml-lint
      uses: ibiqlik/action-yamllint@v1
      with:
        file_or_dir: chopchop.yml
        config_file: .yamllint.yml  
  lint:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - run: |
        cat chopchop.yml | grep "uri:" | sort | uniq -c | sort -n
        test=`cat chopchop.yml | grep "uri:" | sort | uniq -c | grep -v 1 | wc -l`
        if [ $test != 0 ]; then echo "There shouldn't be multiple (and identical) 'uri'. It should be refactored. "; exit 1; fi
